{
    'name': 'Procurement Management Extension',
    'version': '17.0.1.0',
    'category': 'Purchases',
    'author': 'Sofonias B/Temerproperties',
    'summary': 'Restricts requests to single product lines and adds modular menu access rights.',
    'depends': ['procurement_management', 'temer_payment_request', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/picking_technical_verify_wizard_views.xml',
        'views/menu_views.xml',
        'views/internal_request_views_inherit.xml',
        'views/department_request_views_inherit.xml',
        'views/proforma_analysis_views_inherit.xml',
        'views/procurement_request_views_inherit.xml',
        'views/proforma_evaluation_views_inherit.xml',
        'views/payment_integration_views.xml',
        'views/stock_picking_views_inherit.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}