{
    'name': 'Letter Template',
    'version': '17.0.1.0.0',
    'category': 'Collection',
    'summary': 'Dynamic letter templates with header/footer and body management for Collection',
    'author': 'Temerproperties',
    'depends': [
        'collection_management',
        'collection_letter_template',
    ],
    'data': [
        'security/ir.model.access.csv',
        'reports/letter_preview_report.xml',
        'views/letter_type_views.xml',
        'views/letter_director_views.xml',
        'views/letter_number_generator_views.xml',
        'views/letter_type_prefix_views.xml',
        'views/letter_header_footer_views.xml',
        'views/letter_body_views.xml',
        'views/letter_template_views.xml',
        'views/letter_template_action_views.xml',
        'views/letter_type_select_wizard_views.xml',
        'views/letter_saved_views.xml',
        'views/letter_preview_wizard_views.xml',
        'views/print_letter_wizard_inherit_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
