{
    'name': 'Procurement Management',
    'version': '17.0.1.0',
    'category': 'Purchases',
    'author': 'Sofonias B/Temer Properties',
    'summary': 'Streamlined workflow for Department Requests and Purchase Processing',
    'depends': ['purchase', 'stock', 'hr', 'mail', 'purchase_stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/menu_views.xml',
        'views/department_request_views.xml',
        'views/internal_request_views.xml',
        'views/procurement_request_views.xml',
        'views/proforma_analysis_views.xml',
        'views/proforma_evaluation_views.xml',
        'wizard/add_vendor_quotation_views.xml',
        #'views/account_move_views.xml',
        'views/stock_picking_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}