{
    "name": "Temer Commission Center",
    "version": "17.0.1.0.0",
    "category": "Sales/Commission",
    "author": "Sofonias B/Temer Properties",
    "summary": "Centralized commission policies, sheets, and payments for property sales",
    "depends": [
        "base",
        "mail",
        "account",
        "advanced_property_management",
        "temer_structure",
        "collection_management",
    ],
    "data": [
        "security/temer_commission_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/commission_policy_views.xml",
        "views/commission_sheet_views.xml",
        "views/commission_payment_views.xml",
        "views/commission_sheet_line_views.xml",
        "wizards/commission_payment_wizard_views.xml",
        "wizards/commission_cancel_wizard_views.xml",
        "wizards/commission_report_wizard_views.xml",
        "views/commission_menus.xml",
    ],
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
