{
    'name': 'Property Contract Extension',
    'version': '17.0.1.0.0',
    'author': 'Sofonias B/Temer_Properties',
    'summary': 'Extension for Property Contracts',
    'depends': [
        'base', 
        'mail',
        'advanced_property_management', 
        'ahadubit_property_base', 
        'contract_sections',
        'temer_structure',
        'collection_management',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'wizard/void_contract_wizard_views.xml',
        'wizard/void_request_reject_wizard_views.xml',
        'wizard/schedule_amendment_wizard_views.xml',
        'wizard/void_request_approve_wizard_views.xml',
        'views/void_request_views.xml',
        'views/property_sale_views.xml',
        'views/collection_views_ext.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}