{
    'name': 'Collection Management',
    'version': '17.0.1.0.0',
    'category': 'Collection',
    'summary': 'Manage collection follow-ups.',
    'author': 'Sofonias B/temerproperties',
    'depends': [
        'base',
        'mail',
        'ahadubit_property_base',
        'advanced_property_management',
        'temer_configuration_modify',
        ],
    'data': [
        'security/collection_security.xml',
        'security/ir.model.access.csv',
        'security/site_security.xml',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        #'data/server_actions.xml',
        'wizard/print_letter_wizard_views.xml',
        'wizard/payment_wizard_views.xml',
        'wizard/extension_wizard_views.xml',
        'wizard/penalty_apply_wizard_views.xml', 
        'wizard/early_settlement_wizard_views.xml',
        'wizard/send_email_wizard_views.xml',
        'wizard/send_sms_wizard_views.xml',
        'views/collection_views.xml',
        'views/collection_installment_views.xml',
        'views/account_move_views.xml',
        'views/dashboard_views.xml',
        'wizard/milestone_update_wizard_views.xml',
        'views/collection_letterhead_views.xml',
        'views/collection_site_access_views.xml',
        'views/collection_config_views.xml',
        'reports/paperformat_data.xml',
        'reports/collection_report.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'collection_management/static/src/dashboard/**/*',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',

    'uninstall_hook': 'prevent_uninstall_hook',
}