{
    'name': 'Pre Contract Refund',
    'version': '17.0.1.2.6',
    'category': 'Real Estate',
    'summary': 'Manage reservation deposit refunds before contract with approval workflow',
    'author': 'Custom',
    'depends': [
        'mail',
        'account',
        'ahadubit_property_reservation',
        'ahadubit_property_base',
        'advanced_property_management',
        'property_lock_unlock',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/group_cleanup.xml',
        'data/sequence_data.xml',
        'data/product_data.xml',
        'data/refund_type_data.xml',
        'data/refund_reason_data.xml',
        'data/document_label_data.xml',
        'views/customer_bank_views.xml',
        'views/customer_bank_detail_views.xml',
        'views/refund_type_views.xml',
        'views/refund_reason_views.xml',
        'views/pre_contract_refund_views.xml',
        'wizard/pre_contract_refund_reject_wizard_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
