from . import payment
from . import dashboard
from . import collection_order
from . import collection_installment
from . import property_sale_inherit
from . import collection_installment_payment
from . import account_move_inherit
from . import collection_letterhead
from . import res_users
from . import collection_site_access
from . import collection_config
from . import access_control