{
    'name': 'Temer Sales Report',
    'version': '17.0.1.0.11',
    'summary': 'Temer Sales Reports - Sales Deal Closed, Lead Generated, Follow Up, Office Visit, Site Visit, Reservation Report',
    'category': 'Sales',
    'author': 'Temer',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'utm',
        'temer_crm',
        'temer_structure',
        'ahadubit_property_base',
        'ahadubit_property_reservation',
        'advanced_property_management',
        'property_legacy_data',
        'collection_management',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/sales_deal_closed_views.xml',
        'views/lead_generated_views.xml',
        'views/follow_up_views.xml',
        'views/office_visit_views.xml',
        'views/site_visit_views.xml',
        'views/reservation_history_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
